### ISSUE TITLE
Don't know how to get access to apex code

### ISSUE THREAD

**Issue by carlosabella** [coveo/vsforce#105]
Hi, 

I don't know how to get access to my apex code. I build my settings.json and I can execute SOQL. But I don't know how to retrieve a file for coding and deploy it afterwards. 

When I open command palette I don't see any commando to retrieve/deploy a file.

Thank you!

![image](https://cloud.githubusercontent.com/assets/4191627/20660256/e0d6d686-b548-11e6-86f2-180f068b48aa.png)

**Comment by lbenie** [comment]
Hi @carlosabella 

The `Retrieve Package` command fetches everything specified inside your package.xml file inside your project. 

There's a sample [package.xml](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/manifest_samples.htm) from Salesforce.

**Comment by gminero** [comment]
If you would like to access all your Apex classes, you will have to specify it in the package.xml as mentioned by lbenie. Here is a simple package.xml example:
`<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>ApexClass</name>
    </types>

    <version>38.0</version>
</Package>`

other names that you can import are mentioned [here](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_deploy_running_tests.htm):

such as ApexClass
```
ApexComponent
ApexPage
ApexTrigger
```

**Comment by lbenie** [comment]
@carlosabella 
Was your issue resolved ?

**Comment by carlosabella** [comment]
I'm sorry, it's solved!

Thank you!

**Comment by lbenie** [comment]
@carlosabella 

thanks i'm closing this issue then 😄
