### ISSUE TITLE
vsforce breaks PHP syntax highlighting

### ISSUE THREAD

**Issue by williamlang** [coveo/vsforce#115]
### Expected behavior
install vsforce, PHP syntax highlighting works

### Actual behavior
install vsforce, PHP syntax highlight does not work.
Disable vsforce in the workspace, PHP syntax highlighting works again

**Comment by martinytodorov** [comment]
Same here. Now I enable it vsforce specifically for the workspace and its ok.

**Comment by erocheleau** [comment]
Sorry this is too vague to fix something. There can be multiple reasons that seems to create conflicts between two syntax highlighting. If you have specific errors or a simple usecase to reproduce where you cannot use the workaround suggested by @martinytodorov please re-open this.

We are only activating the languages on :

```
"extensions": [
     ".page",
     ".component",
     ".cls",
     ".trigger"
]
```

If this conflicts with some format of php file, then the only option I know of is to disable the extension by workspace.
