### ISSUE TITLE
Error retrieving package

### ISSUE THREAD

**Issue by dennismphil** [coveo/vsforce#116]
I am trying to retrieve a package from a salesforce sandbox environment using the manifest `package.xml` and getting a polling timeout. Maybe allowing for a configurable timeout will help resolve this issue.

### Expected behavior

Running command `vsforce: Retrieve Package` should succeed.

### Actual behavior

Even after multiple trials, getting the same error
```
INFO: Error retrieving package

Parsing package.xml file.
Sending Retrieve Request to Salesforce...
ERROR Error: Polling time out. Process Id = xxxxxxxxxxxxxxxxxxx
```
### Steps to reproduce the behavior

1. Create the manifest `package.xml`
2. Simulate the testing in a slow network environment. For me, it was happening on a sandbox 
3. Run `vsforce: Retrieve Package`

**Comment by bmdelaune** [comment]
I'm having the same issue. Probably should provide a way to change the polling timeout limit.

**Comment by Alex-Dinu** [comment]
Did anyone find a solution for this issue?

**Comment by mrmaramreddy** [comment]
Was this resolved?

**Comment by danjrauch** [comment]
This could be caused by a network issue. I just had a problem downloading a lightning component but then all of a sudden it worked fine.

**Comment by erocheleau** [comment]
Refer to #118 
Changing polling timeouts is an enhancement request.
