### ISSUE TITLE
Cant Retrieve Package

### ISSUE THREAD

**Issue by tr1ple5** [coveo/vsforce#117]
### Expected behavior
retrieve package
### Actual behavior
status just keeps saying retrieve package from salesforce
### Steps to reproduce the behavior
retrieve package.

**Comment by Alex-Dinu** [comment]
You may need to set the loginUrl setting

**Comment by erocheleau** [comment]
There is no error log? There should be an output window.

Please add information here similar to:

instance pod, example: 'na35'
is it a sandbox?
do you have a my domain setup?
Have you tried with the loginUrl?

**Comment by tr1ple5** [comment]
Sorry forgot to close this issue. Thank you!

**Comment by erocheleau** [comment]
What was the problem and solution? :)

**Comment by tr1ple5** [comment]
To be quite honest.. my company decided to use welkin suite as our IDE so I am not sure what the issue was.

**Comment by erocheleau** [comment]
Okay, no problem at all!

There is now a published extension by Salesforce too that has a cool set of features too.

We want this to be stable, but may not include more features and try to contribute to the Salesforce extension instead.
