### ISSUE TITLE
Unpublish from Marketplace

### ISSUE THREAD

**Issue by ntotten** [coveo/vsforce#125]
Hey, I am the PM for the official Salesforce Extensions for VS Code.  If I am not mistaken it looks like work has stopped on this extension and it may not be working anymore. Would you mind unpublishing your extension from the VSCode marketplace so as to avoid any possible confusion about which is the correct Apex extension? Or if you not unpublish maybe rename it to "vsforce (Deprecated)" or something.

Doc: https://code.visualstudio.com/docs/extensions/publish-extension#_unpublishing-extensions

Thanks!

**Comment by tedre191** [comment]
Hi Nathan,

Since Salesforce is now providing a set of extensions, work as indeed stopped on this project.
I've unpublished the extension from the VSCode MarketPlace.

Thanks
